// 모의 메뉴 데이터 (테스트용) TODO : 삭제예정
export const mockMenuData = {
  menuId: 'M_PIIO_00001',
  menuNm: '관리자 최상위메뉴',
  intgSysSeCd: 'PIIO',
  mbrTypeCd: 'MNG',
  upMenuId: null,
  iconClssNm: null,
  sortSeq: 0,
  upendMenuExpsrYn: 'Y',
  lfsdMenuExpsrYn: 'Y',
  scrnUseYn: 'Y',
  scrnId: 'S_PIIO_00001',
  scrnUrlAddr: '/',
  scrnTypeCd: 'M',
  upScrnId: null,
  useYn: 'Y',
  depth: 0,
  children: [
    {
      menuId: 'M_PIIO_00002',
      menuNm: '지원사업 관리',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 1,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00002',
      scrnUrlAddr: 'sprtBiz',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [
        {
          menuId: 'M_PIIO_00009',
          menuNm: '사업공고 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00002',
          iconClssNm: null,
          sortSeq: 1,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00009',
          scrnUrlAddr: 'bizPbanc',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00002',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00011',
              menuNm: '사업정보 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00009',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00011',
              scrnUrlAddr: 'bizInfo',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00009',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00012',
              menuNm: '지원사업 공고관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00009',
              iconClssNm: null,
              sortSeq: 2,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00012',
              scrnUrlAddr: 'sprtBizPbanc',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00009',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00013',
              menuNm: '정책금융관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00009',
              iconClssNm: null,
              sortSeq: 3,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00013',
              scrnUrlAddr: 'plcyFnnc',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00009',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00014',
              menuNm: '주택특별공급 사업공고',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00009',
              iconClssNm: null,
              sortSeq: 4,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00014',
              scrnUrlAddr: 'hsSpcSplyBizPbanc',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00009',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
        {
          menuId: 'M_PIIO_00010',
          menuNm: '신청 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00002',
          iconClssNm: null,
          sortSeq: 2,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00010',
          scrnUrlAddr: 'aply',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00002',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00015',
              menuNm: '신청기업정보',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00010',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00015',
              scrnUrlAddr: 'aplyEntInfo',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00010',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00016',
              menuNm: '지원사업 신청관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00010',
              iconClssNm: null,
              sortSeq: 2,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00016',
              scrnUrlAddr: 'sprtBizAply',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00010',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
      ],
    },
    {
      menuId: 'M_PIIO_00003',
      menuNm: '증명서 발급 관리',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 2,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00003',
      scrnUrlAddr: 'prdocIssu',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [
        {
          menuId: 'M_PIIO_00017',
          menuNm: '증명서 정보 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00003',
          iconClssNm: null,
          sortSeq: 1,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00017',
          scrnUrlAddr: 'prdocInfo',
          scrnTypeCd: 'T',
          upScrnId: 'S_PIIO_00003',
          useYn: 'Y',
          depth: 2,
          children: [],
        },
        {
          menuId: 'M_PIIO_00018',
          menuNm: '증명서 발급 이력',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00003',
          iconClssNm: null,
          sortSeq: 2,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00018',
          scrnUrlAddr: 'prdocIssuHstry',
          scrnTypeCd: 'T',
          upScrnId: 'S_PIIO_00003',
          useYn: 'Y',
          depth: 2,
          children: [],
        },
        {
          menuId: 'M_PIIO_00019',
          menuNm: '증명서 일괄 확인 이력',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00003',
          iconClssNm: null,
          sortSeq: 3,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00019',
          scrnUrlAddr: 'prdocEblcIdntyHstry',
          scrnTypeCd: 'T',
          upScrnId: 'S_PIIO_00003',
          useYn: 'Y',
          depth: 2,
          children: [],
        },
      ],
    },
    {
      menuId: 'M_PIIO_00004',
      menuNm: '정보제공',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 3,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00004',
      scrnUrlAddr: 'infoPvsn',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [
        {
          menuId: 'M_PIIO_00020',
          menuNm: '활용정보 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00004',
          iconClssNm: null,
          sortSeq: 1,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00020',
          scrnUrlAddr: 'utlzInfo',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00004',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00023',
              menuNm: '행사정보',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00023',
              scrnUrlAddr: 'evntInfo',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00024',
              menuNm: '정책뉴스',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 2,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00024',
              scrnUrlAddr: 'plcyNews',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00025',
              menuNm: '입법·행정예고/고시',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 3,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00025',
              scrnUrlAddr: 'lawPbadmsAncmnt',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00026',
              menuNm: '입주기업 모집공고',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 4,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00026',
              scrnUrlAddr: 'mvnEntRcrtPbanc',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00027',
              menuNm: '월간 중기누리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 5,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00027',
              scrnUrlAddr: 'mmJgnr',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00028',
              menuNm: '월간 중기누리 구독자',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 6,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00028',
              scrnUrlAddr: 'mmJgnrSub',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00029',
              menuNm: '기업업무용 서식',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00020',
              iconClssNm: null,
              sortSeq: 7,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00029',
              scrnUrlAddr: 'entTaskTmplt',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00020',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
        {
          menuId: 'M_PIIO_00021',
          menuNm: '고객지원 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00004',
          iconClssNm: null,
          sortSeq: 2,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00021',
          scrnUrlAddr: 'custSprt',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00004',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00030',
              menuNm: '공지사항',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00030',
              scrnUrlAddr: 'ntc',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00031',
              menuNm: 'FAQ',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00031',
              scrnUrlAddr: 'faq',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00032',
              menuNm: 'Q&A',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 3,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00032',
              scrnUrlAddr: 'qna',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00033',
              menuNm: '고객 만족도조사',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 4,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00033',
              scrnUrlAddr: 'custDgstfnExmn',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00034',
              menuNm: '기업가정신 콘텐츠 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 5,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00034',
              scrnUrlAddr: 'entConts',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00035',
              menuNm: '팝업관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 6,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00035',
              scrnUrlAddr: 'popup',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00036',
              menuNm: '배너관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 7,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00036',
              scrnUrlAddr: 'bnr',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00037',
              menuNm: 'SMS 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 8,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00037',
              scrnUrlAddr: 'sms',
              scrnTypeCd: 'M',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [
                {
                  menuId: 'M_PIIO_00130',
                  menuNm: 'SMS 발송',
                  intgSysSeCd: 'PIIO',
                  mbrTypeCd: 'MNG',
                  upMenuId: 'M_PIIO_00037',
                  iconClssNm: null,
                  sortSeq: 1,
                  upendMenuExpsrYn: 'Y',
                  lfsdMenuExpsrYn: 'Y',
                  scrnUseYn: 'Y',
                  scrnId: 'S_PIIO_00130',
                  scrnUrlAddr: 'send',
                  scrnTypeCd: 'T',
                  upScrnId: 'S_PIIO_00037',
                  useYn: 'Y',
                  depth: 4,
                  children: [],
                },
                {
                  menuId: 'M_PIIO_00132',
                  menuNm: 'SMS 양식',
                  intgSysSeCd: 'PIIO',
                  mbrTypeCd: 'MNG',
                  upMenuId: 'M_PIIO_00037',
                  iconClssNm: null,
                  sortSeq: 2,
                  upendMenuExpsrYn: 'Y',
                  lfsdMenuExpsrYn: 'Y',
                  scrnUseYn: 'Y',
                  scrnId: 'S_PIIO_00132',
                  scrnUrlAddr: 'form',
                  scrnTypeCd: 'T',
                  upScrnId: 'S_PIIO_00037',
                  useYn: 'Y',
                  depth: 4,
                  children: [],
                },
              ],
            },
            {
              menuId: 'M_PIIO_00129',
              menuNm: '이메일 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00021',
              iconClssNm: null,
              sortSeq: 9,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00129',
              scrnUrlAddr: 'eml',
              scrnTypeCd: 'M',
              upScrnId: 'S_PIIO_00021',
              useYn: 'Y',
              depth: 3,
              children: [
                {
                  menuId: 'M_PIIO_00131',
                  menuNm: '이메일 발송',
                  intgSysSeCd: 'PIIO',
                  mbrTypeCd: 'MNG',
                  upMenuId: 'M_PIIO_00129',
                  iconClssNm: null,
                  sortSeq: 1,
                  upendMenuExpsrYn: 'Y',
                  lfsdMenuExpsrYn: 'Y',
                  scrnUseYn: 'Y',
                  scrnId: 'S_PIIO_00131',
                  scrnUrlAddr: 'send',
                  scrnTypeCd: 'T',
                  upScrnId: 'S_PIIO_00129',
                  useYn: 'Y',
                  depth: 4,
                  children: [],
                },
                {
                  menuId: 'M_PIIO_00133',
                  menuNm: '이메일 양식',
                  intgSysSeCd: 'PIIO',
                  mbrTypeCd: 'MNG',
                  upMenuId: 'M_PIIO_00129',
                  iconClssNm: null,
                  sortSeq: 2,
                  upendMenuExpsrYn: 'Y',
                  lfsdMenuExpsrYn: 'Y',
                  scrnUseYn: 'Y',
                  scrnId: 'S_PIIO_00133',
                  scrnUrlAddr: 'form',
                  scrnTypeCd: 'T',
                  upScrnId: 'S_PIIO_00129',
                  useYn: 'Y',
                  depth: 4,
                  children: [],
                },
              ],
            },
          ],
        },
        {
          menuId: 'M_PIIO_00022',
          menuNm: '포털 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00004',
          iconClssNm: null,
          sortSeq: 3,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00022',
          scrnUrlAddr: 'prtl',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00004',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00038',
              menuNm: '중소기업 통합플랫폼 소개',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00038',
              scrnUrlAddr: 'smepIntro',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00039',
              menuNm: '안내 콘텐츠 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 2,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00039',
              scrnUrlAddr: 'gdConts',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00040',
              menuNm: '이용약관',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 3,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00040',
              scrnUrlAddr: 'utztnTrms',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00041',
              menuNm: '개인정보처리방침',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 4,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00041',
              scrnUrlAddr: 'prvcPrcsPrcpl',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00042',
              menuNm: '이메일주소 무단 수집 거부안내',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 5,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00042',
              scrnUrlAddr: 'emlAddrClctGd',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00043',
              menuNm: '저작권정책',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 6,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00043',
              scrnUrlAddr: 'cprgtPlcy',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00044',
              menuNm: '웹접근성정책',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 7,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00044',
              scrnUrlAddr: 'webAcsPlcy',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00045',
              menuNm: '포털이미지관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00022',
              iconClssNm: null,
              sortSeq: 8,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00045',
              scrnUrlAddr: 'prtlImg',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00022',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
      ],
    },
    {
      menuId: 'M_PIIO_00005',
      menuNm: '통계/분석',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 4,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00005',
      scrnUrlAddr: 'statsAnls',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [
        {
          menuId: 'M_PIIO_00046',
          menuNm: '통계',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00005',
          iconClssNm: null,
          sortSeq: 1,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00046',
          scrnUrlAddr: 'stats',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00005',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00048',
              menuNm: '통계',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00046',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00048',
              scrnUrlAddr: 'stats',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00046',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
        {
          menuId: 'M_PIIO_00047',
          menuNm: '분석',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00005',
          iconClssNm: null,
          sortSeq: 2,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00047',
          scrnUrlAddr: 'anls',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00005',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00049',
              menuNm: '대시보드',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00047',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00049',
              scrnUrlAddr: 'dsbd',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00047',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
      ],
    },
    {
      menuId: 'M_PIIO_00006',
      menuNm: '시스템 관리',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 5,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00006',
      scrnUrlAddr: 'sys',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [
        {
          menuId: 'M_PIIO_00050',
          menuNm: '회원/권한 관리',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00006',
          iconClssNm: null,
          sortSeq: 1,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00050',
          scrnUrlAddr: 'mbrAuthrt',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00006',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00052',
              menuNm: '회원관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00050',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00052',
              scrnUrlAddr: 'mbr',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00050',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00053',
              menuNm: '통합회원목록',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00050',
              iconClssNm: null,
              sortSeq: 2,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00053',
              scrnUrlAddr: 'intgMbr',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00050',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00054',
              menuNm: '관리자계정 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00050',
              iconClssNm: null,
              sortSeq: 3,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00054',
              scrnUrlAddr: 'mngrAcnt',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00050',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00055',
              menuNm: '권한관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00050',
              iconClssNm: null,
              sortSeq: 4,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00055',
              scrnUrlAddr: 'authrt',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00050',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00056',
              menuNm: '통합로그인 사이트 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00050',
              iconClssNm: null,
              sortSeq: 5,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00056',
              scrnUrlAddr: 'intgLgnSite',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00050',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
        {
          menuId: 'M_PIIO_00051',
          menuNm: '시스템 설정',
          intgSysSeCd: 'PIIO',
          mbrTypeCd: 'MNG',
          upMenuId: 'M_PIIO_00006',
          iconClssNm: null,
          sortSeq: 2,
          upendMenuExpsrYn: 'Y',
          lfsdMenuExpsrYn: 'Y',
          scrnUseYn: 'Y',
          scrnId: 'S_PIIO_00051',
          scrnUrlAddr: 'sysStng',
          scrnTypeCd: 'M',
          upScrnId: 'S_PIIO_00006',
          useYn: 'Y',
          depth: 2,
          children: [
            {
              menuId: 'M_PIIO_00057',
              menuNm: '사용자 메뉴관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00051',
              iconClssNm: null,
              sortSeq: 1,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00057',
              scrnUrlAddr: 'userMenu',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00051',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00058',
              menuNm: '관리자 메뉴관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00051',
              iconClssNm: null,
              sortSeq: 2,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00058',
              scrnUrlAddr: 'mngrMenu',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00051',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00059',
              menuNm: '게시판 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00051',
              iconClssNm: null,
              sortSeq: 3,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00059',
              scrnUrlAddr: 'bbs',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00051',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00060',
              menuNm: '공통코드관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00051',
              iconClssNm: null,
              sortSeq: 4,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00060',
              scrnUrlAddr: 'comCd',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00051',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00061',
              menuNm: '보안설정',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00051',
              iconClssNm: null,
              sortSeq: 5,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00061',
              scrnUrlAddr: 'scrtyStng',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00051',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
            {
              menuId: 'M_PIIO_00062',
              menuNm: 'API 연계 관리',
              intgSysSeCd: 'PIIO',
              mbrTypeCd: 'MNG',
              upMenuId: 'M_PIIO_00051',
              iconClssNm: null,
              sortSeq: 6,
              upendMenuExpsrYn: 'Y',
              lfsdMenuExpsrYn: 'Y',
              scrnUseYn: 'Y',
              scrnId: 'S_PIIO_00062',
              scrnUrlAddr: 'apiLink',
              scrnTypeCd: 'T',
              upScrnId: 'S_PIIO_00051',
              useYn: 'Y',
              depth: 3,
              children: [],
            },
          ],
        },
      ],
    },
    {
      menuId: 'M_PIIO_00007',
      menuNm: 'AI서비스 관리',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 6,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00007',
      scrnUrlAddr: 'aiSrvc',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [],
    },
    {
      menuId: 'M_PIIO_00008',
      menuNm: '데이터레이크 관리',
      intgSysSeCd: 'PIIO',
      mbrTypeCd: 'MNG',
      upMenuId: 'M_PIIO_00001',
      iconClssNm: null,
      sortSeq: 7,
      upendMenuExpsrYn: 'Y',
      lfsdMenuExpsrYn: 'Y',
      scrnUseYn: 'Y',
      scrnId: 'S_PIIO_00008',
      scrnUrlAddr: 'dataLake',
      scrnTypeCd: 'M',
      upScrnId: 'S_PIIO_00001',
      useYn: 'Y',
      depth: 1,
      children: [],
    },
  ],
};
