export const PUBLIC_ANNOUNCEMENT_TYPE = {
  BUSINESS: 'BIZPBN',
  HOUSING_SPECIAL_SUPPLY: 'HSSPLY',
};

export const SUPPORT_BUSINESS_RELATED_ANNOUNCEMENT_TYPES = [
  PUBLIC_ANNOUNCEMENT_TYPE.BUSINESS,
  PUBLIC_ANNOUNCEMENT_TYPE.HOUSING_SPECIAL_SUPPLY,
].join(',');
